In [19]:
import pandas as pd
import numpy as np

In [2]:
rate = pd.read_csv("Survey_raw.csv")

In [5]:
rate.head()

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,3-3_1,3-4_1,3-5_1,3-6_1,3-7_1,3-8_1,3-9_1,3-10_1,2-11_1.1,2-12_1.1
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,Starfish - Typicality Least to Most,Starfish - Typicality Least to Most,Starfish - Typicality Least to Most,Starfish - Typicality Least to Most,Starfish - Typicality Least to Most,Starfish - Typicality Least to Most,Starfish - Typicality Least to Most,Starfish - Typicality Least to Most,Starfish - Typicality Least to Most,Starfish - Typicality Least to Most
1,"{""ImportId"":""startDate"",""timeZone"":""America/De...","{""ImportId"":""endDate"",""timeZone"":""America/Denv...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""America...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""QID44_1""}","{""ImportId"":""QID45_1""}","{""ImportId"":""QID46_1""}","{""ImportId"":""QID47_1""}","{""ImportId"":""QID48_1""}","{""ImportId"":""QID49_1""}","{""ImportId"":""QID50_1""}","{""ImportId"":""QID51_1""}","{""ImportId"":""QID52_1""}","{""ImportId"":""QID53_1""}"
2,2022-05-02 13:33:22,2022-05-02 13:34:00,1,NaN,100,37,1,2022-05-02 13:34:01,R_3LcAIjlSvZyMqoP,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-05-02 13:43:08,2022-05-02 13:48:21,0,174.250.2.5,100,313,1,2022-05-02 13:48:22,R_2YxrD4cRvE19DM0,NaN,...,2,6,5,4,3,2,2,4,4,5
4,2022-05-02 13:47:37,2022-05-02 13:49:48,0,66.65.189.195,100,130,1,2022-05-02 13:49:48,R_yxSPOhQ4rG7PY9b,NaN,...,2,7,7,7,7,2,3,4,5,7

In [9]:
rate = rate.iloc[:, range(17, 53)]

clean_rate = rate.iloc[3:36, :]

rate = clean_rate.to_numpy()

rate = rate.astype(np.float)

par_avg = np.nanmean(rate, axis = 0)

par_avg.shape

In [34]:
np.savetxt("avg.csv", par_avg, delimiter=",")